// File generated by FlutterFire CLI for Firebase project: college-event-managent
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnOGQbJCK5TwKyYsZxFanUU4gzt84IQG8',
    appId: '1:882482595825:web:99f13ebe79419d6857a650',
    messagingSenderId: '882482595825',
    projectId: 'college-event-managent',
    authDomain: 'college-event-managent.firebaseapp.com',
    storageBucket: 'college-event-managent.firebasestorage.app',
    measurementId: 'G-NL825PPD4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnLnUUC1ZaViiVvh9k7y9Yc0yvf2VSlaE',
    appId: '1:882482595825:android:5b23cf9521476f0957a650',
    messagingSenderId: '882482595825',
    projectId: 'college-event-managent',
    storageBucket: 'college-event-managent.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9TswCN-kMYiKfkOmQ_B7gy7Ni7Zz9MNk',
    appId: '1:882482595825:ios:7123917fe5790c5c57a650',
    messagingSenderId: '882482595825',
    projectId: 'college-event-managent',
    storageBucket: 'college-event-managent.firebasestorage.app',
    iosBundleId: 'com',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9TswCN-kMYiKfkOmQ_B7gy7Ni7Zz9MNk',
    appId: '1:882482595825:ios:7123917fe5790c5c57a650',
    messagingSenderId: '882482595825',
    projectId: 'college-event-managent',
    storageBucket: 'college-event-managent.firebasestorage.app',
    iosBundleId: 'com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnOGQbJCK5TwKyYsZxFanUU4gzt84IQG8',
    appId: '1:882482595825:web:a393905f8c7e4f7257a650',
    messagingSenderId: '882482595825',
    projectId: 'college-event-managent',
    authDomain: 'college-event-managent.firebaseapp.com',
    storageBucket: 'college-event-managent.firebasestorage.app',
    measurementId: 'G-XBDRSJJHBC',
  );
}
